
# create user
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
    "firstname":"Eugene",
     "email":"eugenekorir12@gmail.com",
     "lastname":"korir", 
     "isAdmin":true,
    "password":"@Eugene123"
}


### login

POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
    "email":"eugenekorir12@gmail.com", 
    "password":"@Eugene123"
}

### reset password

POST http://localhost:3001/api/auth/reset-password
Content-Type: application/json 

{
    "userId": "ca394499-97da-478a-903b-f109cba61731",
    "password":"@Caleb123"
}

### forgot password

POST http://localhost:3001/api/auth/forgot-password
Content-Type: application/json 

{
   "email":"eugenekorir11@gmail.com"
}

### update user

PUT http://localhost:3001/api/auth
Content-Type: application/json
x-auth-token :Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV1Z2VuZWtvcmlyMTJAZ21haWwuY29tIiwiaWQiOiJiMTJjYzVlOS02YjBlLTRiM2QtYmYyZS0wODkxNDlmYWJhZWEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2Mzk5MDc4MjYsImV4cCI6MTYzOTk5NDIyNn0.14bOdymG1StUQay0E-nYeNIJ04aj7CQ-Gk7t21qkYIA"

{
    "id":"ca394499-97da-478a-903b-f109cba61731",
    "firstname": "jonathan",
    "lastname": "mwaniki",
    "email":"jonathan@gmail.com"
}

### delete user

PUT http://localhost:3001/api/auth/delete
Content-Type: application/json

{
    "email":"jonathan@gmail.com"   
}


###

GET http://localhost:3001/api/auth
Authorization:  :Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV1Z2VuZWtvcmlyMTJAZ21haWwuY29tIiwiaWQiOiJiMTJjYzVlOS02YjBlLTRiM2QtYmYyZS0wODkxNDlmYWJhZWEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2Mzk5ODE2NDIsImV4cCI6MTY0MDA2ODA0Mn0.GBQu1CPRF_giv8ccJLguOs8s-fvYOR_pi_ruuBtIYhY


###

GET http://localhost:3001/api/auth/ca394499-97da-478a-903b-f109cba61731

