### create project
POST http://localhost:3002/projects
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV1Z2VuZWtvcmlyMTJAZ21haWwuY29tIiwiaWQiOiJiMTJjYzVlOS02YjBlLTRiM2QtYmYyZS0wODkxNDlmYWJhZWEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NDAyNjQxNzIsImV4cCI6MTY0MDM1MDU3Mn0.UNBjPqfYJGgS6Bl-eQV3MYyBQd1MGpLgLdTPUnbziWo

{
    "name":" project1",
    "client_name":"yahoo",
    "start_date":"2021, 12, 15",
    "end_date":"2021, 12, 15",
    "description":"deleting  tasks"
}

### get all projects

GET http://localhost:3002/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV1Z2VuZWtvcmlyMTJAZ21haWwuY29tIiwiaWQiOiJiMTJjYzVlOS02YjBlLTRiM2QtYmYyZS0wODkxNDlmYWJhZWEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NDA2MjMyMjcsImV4cCI6MTY0MDcwOTYyN30.kb_mqsuNfJ_0X5lf2aGmlc9xi8ubOPN48YFaOe2IdEg


### get single project

GET http://localhost:3002/projects/9c1a40c8-1891-4afa-96b7-703ef8ed4c23


### update project
PUT  http://localhost:3002/projects
Content-Type: application/json

{
    "project_id":"9c1a40c8-1891-4afa-96b7-703ef8ed4c23",
    "name":"first updated project",
    "client_name":"onQ",
    "start_date":"1995, 11, 17",
    "end_date":"1995, 11, 20",
    "description":"getting tasks"
}

### get assigned user to look
GET  http://localhost:3002/projects/assign/cb985ef2-af77-44a6-bbcf-55fab5d1fe4a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV1Z2VuZWtvcmlyMTJAZ21haWwuY29tIiwiaWQiOiJiMTJjYzVlOS02YjBlLTRiM2QtYmYyZS0wODkxNDlmYWJhZWEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NDA2MjMyMjcsImV4cCI6MTY0MDcwOTYyN30.kb_mqsuNfJ_0X5lf2aGmlc9xi8ubOPN48YFaOe2IdEg

### assign project
POST  http://localhost:3002/projects/assign
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV1Z2VuZWtvcmlyMTJAZ21haWwuY29tIiwiaWQiOiJiMTJjYzVlOS02YjBlLTRiM2QtYmYyZS0wODkxNDlmYWJhZWEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NDAxNTcwNjIsImV4cCI6MTY0MDI0MzQ2Mn0.4pj35rzRp-Grp40BTqjoN7X6nPugwxOy9U7GyJsg6AU

{
    "project_id":"4b363d9c-c24f-409f-8bb0-7473a322e18e",
    "user_id":"b12cc5e9-6b0e-4b3d-bf2e-089149fabaea"
}

### unassign project look
POST  http://localhost:3002/projects/unassign
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV1Z2VuZWtvcmlyMTJAZ21haWwuY29tIiwiaWQiOiJiMTJjYzVlOS02YjBlLTRiM2QtYmYyZS0wODkxNDlmYWJhZWEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NDAxNTcwNjIsImV4cCI6MTY0MDI0MzQ2Mn0.4pj35rzRp-Grp40BTqjoN7X6nPugwxOy9U7GyJsg6AU

{
    "project_id":"9c1a40c8-1891-4afa-96b7-703ef8ed4c23"
}

### delete project
PUT   http://localhost:3002/projects/delete
Content-Type: application/json

{
    "project_id":"2280a200-2278-4eaf-98f0-2696f74adadd"
}