# create task
POST http://localhost:3002/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV1Z2VuZWtvcmlyMTJAZ21haWwuY29tIiwiaWQiOiJiMTJjYzVlOS02YjBlLTRiM2QtYmYyZS0wODkxNDlmYWJhZWEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NDAxNTcwNjIsImV4cCI6MTY0MDI0MzQ2Mn0.4pj35rzRp-Grp40BTqjoN7X6nPugwxOy9U7GyJsg6AU

{
    "project_id":"9c1a40c8-1891-4afa-96b7-703ef8ed4c23",
    "name":"Task1",
    "start_date":"1995-11-16",
    "end_date":"1995-11-17",
    "description":"first task",
    "duration":"24"
}

### get all tasks
GET http://localhost:3002/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV1Z2VuZWtvcmlyMTJAZ21haWwuY29tIiwiaWQiOiJiMTJjYzVlOS02YjBlLTRiM2QtYmYyZS0wODkxNDlmYWJhZWEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NDA2MjMyMjcsImV4cCI6MTY0MDcwOTYyN30.kb_mqsuNfJ_0X5lf2aGmlc9xi8ubOPN48YFaOe2IdEg

### get one task

GET http://localhost:3002/tasks/9c1a40c8-1891-4afa-96b7-703ef8ed4c23/5b106a26-cfe6-42a7-8cc6-216e6080d54f

### delete task
PUT  http://localhost:3002/tasks/delete
Content-Type: application/json

{
    "task_id":"a0c66397-c074-442a-ac72-e13a1f8bb61f",
    "project_id":"9c1a40c8-1891-4afa-96b7-703ef8ed4c23"
}
### update task
PUT http://localhost:3002/tasks
Content-Type: application/json

{
    "task_id":"5b106a26-cfe6-42a7-8cc6-216e6080d54f",
    "project_id":"9c1a40c8-1891-4afa-96b7-703ef8ed4c23",
    "name":"updated Task1",
    "start_date":"1995-11-16",
    "end_date":"1995-11-17",
    "description":"first task",
    "duration":"24"
}

### assign task
POST http://localhost:3002/tasks/assign
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV1Z2VuZWtvcmlyMTJAZ21haWwuY29tIiwiaWQiOiJiMTJjYzVlOS02YjBlLTRiM2QtYmYyZS0wODkxNDlmYWJhZWEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NDAxNTcwNjIsImV4cCI6MTY0MDI0MzQ2Mn0.4pj35rzRp-Grp40BTqjoN7X6nPugwxOy9U7GyJsg6AU

{
    "project_id":"9c1a40c8-1891-4afa-96b7-703ef8ed4c23",
    "task_id":"5b106a26-cfe6-42a7-8cc6-216e6080d54f",
    "user_id":"b12cc5e9-6b0e-4b3d-bf2e-089149fabaea"
}
### unassign task
POST  http://localhost:3002/tasks/unassign
Content-Type: application/json

{
    "task_id":"5b106a26-cfe6-42a7-8cc6-216e6080d54f",
    "project_id":"9c1a40c8-1891-4afa-96b7-703ef8ed4c23"
}

### get assigned user
GET http://localhost:3002/tasks/assign/5b106a26-cfe6-42a7-8cc6-216e6080d54f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV1Z2VuZWtvcmlyMTJAZ21haWwuY29tIiwiaWQiOiJiMTJjYzVlOS02YjBlLTRiM2QtYmYyZS0wODkxNDlmYWJhZWEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NDA2NzkwODgsImV4cCI6MTY0MDc2NTQ4OH0.KbPnfnC_DF5k225tT250P_VPxVQzFRgoWBcEIxCCoSM



###
PUT  http://localhost:8082/api/tasks/complete
Content-Type: application/json

{
    "task_id":"e36e87e8-527c-4038-b1ff-1f22f82da0d6",
    "project_id":"3c72eba6-b967-4fee-bb8d-7deed7778908"
}

###

GET http://localhost:3002/tasks/user/93a05202-4845-4736-b354-f1bf1b12fb5e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV1Z2VuZWtvcmlyMTJAZ21haWwuY29tIiwiaWQiOiJmMTA5Y2U3Yy01YjYxLTQ4MGMtYWVkZC1lNjdkYWExNjdiNzYiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NDEzODM4MzAsImV4cCI6MTY0MTQ3MDIzMH0.3_WG-HmKPb5D_J0T3RHtWVNIElSzlL49tacqfPllwsc