# create task
POST http://localhost:3002/tasks
Content-Type: application/json

{
    "project_id":"9c1a40c8-1891-4afa-96b7-703ef8ed4c23",
    "name":"Task1",
    "start_date":"1995-11-16",
    "end_date":"1995-11-17",
    "description":"first task",
    "duration":"24"
}

### get all tasks
GET http://localhost:3002/tasks/9c1a40c8-1891-4afa-96b7-703ef8ed4c23

### get one task

GET http://localhost:3002/tasks/9c1a40c8-1891-4afa-96b7-703ef8ed4c23/5b106a26-cfe6-42a7-8cc6-216e6080d54f

### delete task
PUT  http://localhost:3002/tasks/delete
Content-Type: application/json

{
    "task_id":"a0c66397-c074-442a-ac72-e13a1f8bb61f",
    "project_id":"9c1a40c8-1891-4afa-96b7-703ef8ed4c23"
}
### update task
PUT http://localhost:3002/tasks
Content-Type: application/json

{
    "task_id":"5b106a26-cfe6-42a7-8cc6-216e6080d54f",
    "project_id":"9c1a40c8-1891-4afa-96b7-703ef8ed4c23",
    "name":"updated Task1",
    "start_date":"1995-11-16",
    "end_date":"1995-11-17",
    "description":"first task",
    "duration":"24"
}

### assign task
POST http://localhost:3002/tasks/assign
Content-Type: application/json

{
    "project_id":"9c1a40c8-1891-4afa-96b7-703ef8ed4c23",
    "task_id":"5b106a26-cfe6-42a7-8cc6-216e6080d54f",
    "user_id":"4df9ff7f-a9ba-42f9-9b2e-ed2902381d26"
}
### unassign task
POST  http://localhost:3002/tasks/unassign
Content-Type: application/json

{
    "task_id":"5b106a26-cfe6-42a7-8cc6-216e6080d54f",
    "project_id":"9c1a40c8-1891-4afa-96b7-703ef8ed4c23"
}

### get assigned user
GET http://localhost:3002/tasks/assign/5b106a26-cfe6-42a7-8cc6-216e6080d54f

###
PUT  http://localhost:8082/api/tasks/complete
Content-Type: application/json

{
    "task_id":"e36e87e8-527c-4038-b1ff-1f22f82da0d6",
    "project_id":"3c72eba6-b967-4fee-bb8d-7deed7778908"
}