export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const GET_UNASSIGNEDUSERS_FAIL = "GET_UNASSIGNEDUSERS_FAIL";
export const GET_UNASSIGNEDUSERS_SUCCESS = "GET_UNASSIGNEDUSERS_SUCCESS";
export const GET_UNASSIGNEDUSERS_REQUEST = "GET_UNASSIGNEDUSERS_REQUEST";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const GET_PROJECTS_REQUEST = "GET_PROJECTS_REQUEST";
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const GET_PROJECTS_FAIL = "GET_PROJECTS_FAIL";
export const GET_TASKS_REQUEST = "GET_TASKS_REQUEST";
export const GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS";
export const GET_TASKS_FAIL = "GET_TASKS_FAIL";
export const ADD_PROJECT_REQUEST = "ADD_PROJECT_REQUEST";
export const ADD_PROJECT_SUCCESS = "ADD_PROJECT_SUCCESS";
export const ADD_PROJECT_FAIL = "ADD_PROJECT_FAIL";
export const ASSIGN_TASK_REQUEST = "ASSIGN_TASK_REQUEST";
export const ASSIGN_TASK_SUCCESS = "ASSIGN_TASK_SUCCESS";
export const ASSIGN_TASK_FAIL = "ASSIGN_TASK_FAIL";
export const ADD_TASK_REQUEST = "ADD_TASK_REQUEST";
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const ADD_TASK_FAIL = "ADD_TASK_FAIL";

export const COMPLETE_TASK_REQUEST = "COMPLETE_TASK_REQUEST";
export const COMPLETE_TASK_SUCCESS = "COMPLETE_TASK_SUCCESS";
export const COMPLETE_TASK_FAIL = "COMPLETE_TASK_FAIL";

export const UNCOMPLETE_TASK_REQUEST = "UNCOMPLETE_TASK_REQUEST";
export const UNCOMPLETE_TASK_SUCCESS = "UNCOMPLETE_TASK_SUCCESS";
export const UNCOMPLETE_TASK_FAIL = "UNCOMPLETE_TASK_FAIL";

export const DELETE_TASK_REQUEST = "DELETE_TASK_REQUEST";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_FAIL = "DELETE_TASK_FAIL";

export const UNASSIGN_TASK_REQUEST = "UNASSIGN_TASK_REQUEST";
export const UNASSIGN_TASK_SUCCESS = "UNASSIGN_TASK_SUCCESS";
export const UNASSIGN_TASK_FAIL = "UNASSIGN_TASK_FAIL";

export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";

export const GET_ASSIGNED_USERS_PROJECT_REQUEST =
  "GET_ASSIGNED_USERS_PROJECT_REQUEST";
export const GET_ASSIGNED_USERS_PROJECT_SUCCESS =
  "GET_ASSIGNED_USERS_PROJECT_SUCCESS";
export const GET_ASSIGNED_USERS_PROJECT_FAIL =
  "GET_ASSIGNED_USERS_PROJECT_FAIL";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_FAIL = "DELETE_PROJECT_FAIL";

export const UPDATE_PROJECT_REQUEST = "UPDATE_PROJECT_REQUEST";
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";
export const UPDATE_PROJECT_FAIL = "UPDATE_PROJECT_FAIL";

export const UPDATE_TASK_REQUEST = "UPDATE_TASK_REQUEST";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const UPDATE_TASK_FAIL = "UPDATE_TASK_FAIL";
